version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: books
      DB_USER: postgres
      DB_PASS: password
    depends_on:
      - db

volumes:
  pg_data:
